// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsC3FFsUp_Yl00rqyqdcc1k0dsK_xmb3w',
    appId: '1:1071845027758:web:47a5a3021f10c16135e23f',
    messagingSenderId: '1071845027758',
    projectId: 'taskmate-77545',
    authDomain: 'taskmate-77545.firebaseapp.com',
    storageBucket: 'taskmate-77545.appspot.com',
    measurementId: 'G-4YQ722519X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvzScIjvjEjxzdUPryf6tKzZ_zsAMk0Yo',
    appId: '1:1071845027758:android:27e957f9aef4168a35e23f',
    messagingSenderId: '1071845027758',
    projectId: 'taskmate-77545',
    storageBucket: 'taskmate-77545.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcUfNmC7ILQtE2aPN6r8mOxm3hOu7gCLI',
    appId: '1:1071845027758:ios:0f05ed7a35563a4235e23f',
    messagingSenderId: '1071845027758',
    projectId: 'taskmate-77545',
    storageBucket: 'taskmate-77545.appspot.com',
    iosBundleId: 'com.example.taskMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcUfNmC7ILQtE2aPN6r8mOxm3hOu7gCLI',
    appId: '1:1071845027758:ios:6e1cddddb5e3207135e23f',
    messagingSenderId: '1071845027758',
    projectId: 'taskmate-77545',
    storageBucket: 'taskmate-77545.appspot.com',
    iosBundleId: 'com.example.taskMate.RunnerTests',
  );
}
